import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
// import CustomEditor from '../comp/CustomEditor'
import styles from '../styles/Home.module.scss'

const CustomEditor = dynamic(()=>import('../comp/CustomEditor'),{ssr:false})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Editor JS Rich Text </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heading}>
        <h1>Editor Js Rich Text Editor</h1>
        </div>
       
     <CustomEditor />
      </main>

    </div>
  )
}

export default Home
